### ISSUE TITLE
Title Hierarchy

### ISSUE THREAD

**Issue by aubertc** [idleberg/Creative-Commons-Markdown#16]
Hi,

Maybe more of a question that an issue per se.

Your files start with 

```markdown
## creative commons

# Attribution-NonCommercial-NoDerivatives 4.0 International
```

or similarly.

Why are you starting with a level 2 header (`##`) and then following with a level 1 header (`#`)?

As far as I know, and e.g. [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes) says the same, we should 

> Avoid skipping heading levels: always start from `<h1>`, next use `<h2>` and so on.

So, why this choice?

**Comment by idleberg** [comment]
This is correct and has been fixed in 79c9f14a3c1a6ce5f68eb3b2ffe9997d054999ec. Thanks for reporting!
