### ISSUE TITLE
Missing boldface

### ISSUE THREAD

**Issue by fkohrt** [idleberg/Creative-Commons-Markdown#17]
According to [Legal Code Defined](https://creativecommons.org/legal-code-defined/), the "Formatting of license text (bold, italic, underline, etc.)" is part of the legal code. It should therefore be reproduced exactly. I found at least one deviation (haven't searched for others) at [CC BY 4.0](https://github.com/idleberg/Creative-Commons-Markdown/blob/a76604a/4.0/by.markdown), Section 1, letter k.

The correct emphasis should be ("Your" in boldface):

> **You** means the individual or entity exercising the Licensed Rights under this Public License. **Your** has a corresponding meaning.

This probably should also be fixed in the other CC BY-* licenses.

**Comment by idleberg** [comment]
Good find, thank you. This was fixed in f393b994420afeb10dfef9aa6891a2b77702d33e!
