### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by alexfornuto** [idleberg/Creative-Commons-Markdown#21]
Ironically, this repo doesn't include a LICENSE file, so technically we cannot reuse these formats of the CC license you've created :)

**Comment by idleberg** [comment]
If I remember correctly, Creative Commons does not specify a license for their licenses and I would (have to) follow whatever they specify. However, in the Node manifest currently uses a [public domain](https://github.com/idleberg/Creative-Commons-Markdown/blob/90e6baffa582ed7942ef3a94edd5da432553e08f/package.json#L6=) license.

**Comment by saltq144** [comment]
Creative Commons licenses are licensed under CC0. See [here](https://creativecommons.org/policies#licensing%20statement).

**Comment by idleberg** [comment]
@saltq144 Thank you! Fixed in v0.4.1
