### ISSUE TITLE
Earlier CC-BY licenses

### ISSUE THREAD

**Issue by dhimmel** [idleberg/Creative-Commons-Markdown#5]
Greetings @idleberg, thanks for posting these markdown formatted licenses.

Any chance you will do the same for earlier versions (e.g. 3.0 and before)?

I always use the latest version, but sometimes I am including the license for work someone has previously published under a `< 4.0` licensed.

**Comment by idleberg** [comment]
I didn't plan to, but I might when I have more time

**Comment by dhimmel** [comment]
Awesome, your github is the *goto* location for Creative Commons Licenses formatted in markdown.

**Comment by idleberg** [comment]
fixed in 836c9263ecd452fb7358bbe40ed3b155d1885763

**Comment by dhimmel** [comment]
Thanks -- that was fast!
