### ISSUE TITLE
Do we still need two branches/versions?

### ISSUE THREAD

**Issue by nyeates** [idleberg/Creative-Commons-Markdown#7]
Now that CommonMark is up live on all of GitHub, does the tab version look correctly rendered? If so, do we need two branches/versions still?

I would volunteer to clean up the repo, but I am unsure on the answers.

**Comment by nyeates** [comment]
@idleberg I forgot to at-tag you to get your attn. Let me know your thoughts...

**Comment by idleberg** [comment]
Probably not, but the spaces version could needs to be overworked. Will look into it after the weekend or so.

**Comment by idleberg** [comment]
Removed the `tabulators` branch and renames `spaces` to `master`, added tagged releases
